language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t cristianasp/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true cristianasp/react-app npm run test   
